use_frameworks!

platform :ios, '12.0'

target 'ImageCoreEngineTool_Example' do
  pod 'ImageCoreEngineTool', :path => '../'

  target 'ImageCoreEngineTool_Tests' do
    inherit! :search_paths

    
  end
end
